global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'canton-validator'
    static_configs:
      - targets: ['validator:10013']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '.*'
        action: keep

  - job_name: 'canton-participant'
    static_configs:
      - targets: ['participant:10013']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['canton-node-exporter:9101']
